# Simplified Nash Equalibrium 

Assume Player 1 checks on the opening move no matter what card he has.

Denote Player 1's card as $C_1$ and Player 2's card as $C_2$: $C_1, C_2 \in \{J, Q, K\}$

Denote Player 2's action as $A_2 \in \{bet, check\}$

Denote Player 1's action after Player 2 bets as $A_1 \in \{call, fold\}$

The conditional probabilities $P(A_2|C_2)$ and $P(A_1|C_1)$ are given in the table below:

![alt text](images/probs.png "conditoinal probs")

## Find Nash Equalibrium value for q

In Player 2's turn, if he has J and bets, the outcome will be:
1) -2 if Player 1 has Q and calls with probability $q$
2) +1 if Player 1 has Q and checks with probability $1-q$
3) -2 if Player 1 has K (and calls with certainty)

$$E[R_2|A_2=bet] = P(C_1=Q)P(A_1=call|C_1=Q)\cdot(-2) + P(C_1=Q)P(A_1=fold|C_1=Q)\cdot 1 + P(C_1=K) \cdot(-2) = -\frac{1}{2} -\frac{3}{2}q$$

If Player 2 checks, he will certainly lose

$$E[R|A_2=check] = -1$$

To achieve Nash Equalibrium, Player 2 should be indifferent in the decision of bet or check. We have:

$$-\frac{1}{2} -\frac{3}{2}q = -1 \Rightarrow q = \frac{1}{3}$$

## Find Nash Equalibrium value for p

In Player 1's turn after Player 2 already bets, if Player 1 calls, the outcome will then depend on what card that Player 2 holds. Apply Bayes' rule to find out the probability conditioned on Player 2 bets:

$$P(C_2=J|A_2=bet) = \frac{P(A_2=bet|C_2=J)P(C_2=J)}{P(A_2=bet|C_2=J)P(C_2=J) + P(A_2=bet|C_2=K)P(C_2=K)} = \frac{p}{1+p}$$

$$P(C_2=K|A_2=bet) = \frac{P(A_2=bet|C_2=K)P(C_2=K)}{P(A_2=bet|C_2=J)P(C_2=J) + P(A_2=bet|C_2=K)P(C_2=K)} = \frac{1}{1+p}$$

Similarly, apply indifference property:

$$E[R_1|A_1=call] = 2\cdot\frac{p-1}{p+1} = E[R_1|A_1=fold]=-1 \Rightarrow p=\frac{1}{3}$$

In [1]:
import numpy as np

In [14]:
np.random.choice(3)

1

In [15]:
p = np.array([0, 0.5,0.5])

In [16]:
np.where(p>0)

(array([1, 2]),)

In [17]:
a = np.array(range(5))

In [18]:
a

array([0, 1, 2, 3, 4])

In [19]:
ix = np.random.choice([True, False], size=5)

In [20]:
ix

array([False, False,  True,  True,  True])

In [21]:
a[ix] = 100

In [22]:
a

array([  0,   1, 100, 100, 100])

In [23]:
True in ix

True

In [24]:
a

array([  0,   1, 100, 100, 100])

In [25]:
lix = np.array([1,2])

In [26]:
lix

array([1, 2])

In [27]:
a[lix]

array([  1, 100])

In [ ]:
how 